# Generated by Django 6.0.2 on 2026-02-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this role.', to='auth.permission', verbose_name='Permissions'),
        ),
    ]
