# Generated by Django 6.0.2 on 2026-02-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_users', 'Admin-level user management')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
