"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

Environment is read from WP-Project/.env (loaded via python-dotenv at startup).
No OS/system exports are required for local development — just create .env and run.

Layout reference:
  WP-Project/
    backend/
      backend/
        settings.py  <- this file   (parents[0] = backend/backend/)
      manage.py                     (parents[1] = backend/)
    .env                            (parents[2] = WP-Project/ = ROOT_DIR)
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Callable
from datetime import timedelta

# ── Path resolution ────────────────────────────────────────────────────────────
# BASE_DIR : WP-Project/backend/  (Django project root, where manage.py lives)
# ROOT_DIR : WP-Project/          (repo root, where .env lives)
BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = Path(__file__).resolve().parents[2]

# ── Load .env from repo root ───────────────────────────────────────────────────
from dotenv import load_dotenv  # noqa: E402

load_dotenv(ROOT_DIR / ".env")   # does nothing if file absent; silent in prod

# ── env_get – typed environment variable helper ────────────────────────────────

def env_get(
    key: str,
    default: Any = None,
    cast: Callable = str,
    required: bool = False,
) -> Any:
    """
    Retrieve *key* from the environment and cast it to *cast*.

    Supported cast values
    ─────────────────────
    str          : (default) raw string value
    int          : integer
    float        : floating-point
    bool         : case-insensitive true/false/1/0/yes/no/on/off
    list         : comma-separated values; each element is stripped and
                   empty entries are removed

    Parameters
    ──────────
    key       : environment variable name
    default   : value returned when the variable is absent or empty
    cast      : callable that converts the raw string (use built-in types or
                the *list* sentinel for list[str])
    required  : when True, a missing/empty variable raises RuntimeError

    Raises
    ──────
    RuntimeError – if required=True and variable is absent/empty
    RuntimeError – if the raw value cannot be cast to the requested type
    """
    raw: str | None = os.environ.get(key)

    if raw is None or raw.strip() == "":
        if required:
            raise RuntimeError(
                f"[settings] Required environment variable '{key}' is not set. "
                f"Add it to WP-Project/.env (or export it in the environment)."
            )
        return default

    # ── bool ────────────────────────────────────────────────────────────────
    if cast is bool:
        lowered = raw.strip().lower()
        if lowered in {"true", "1", "yes", "on"}:
            return True
        if lowered in {"false", "0", "no", "off"}:
            return False
        raise RuntimeError(
            f"[settings] Cannot cast '{key}'='{raw}' to bool. "
            f"Accepted values (case-insensitive): true/false/1/0/yes/no/on/off."
        )

    # ── list[str] ────────────────────────────────────────────────────────────
    if cast is list:
        return [item.strip() for item in raw.split(",") if item.strip()]

    # ── str / int / float / any callable ────────────────────────────────────
    try:
        return cast(raw.strip())
    except (ValueError, TypeError) as exc:
        raise RuntimeError(
            f"[settings] Cannot cast '{key}'='{raw}' to {getattr(cast, '__name__', cast)}: {exc}"
        ) from exc


# ==============================================================================
# SECURITY
# ==============================================================================

SECRET_KEY = env_get("SECRET_KEY", required=True)

DEBUG = env_get("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = env_get(
    "ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1"],
    cast=list,
)

CSRF_TRUSTED_ORIGINS = env_get(
    "CSRF_TRUSTED_ORIGINS",
    default=["http://localhost:5173"],
    cast=list,
)

# ==============================================================================
# APPLICATION DEFINITION
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Project apps
    'accounts',
    'evidence',
    'core',
    'board',
    'cases',
    'suspects',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
]

MIDDLEWARE = [
    # CorsMiddleware MUST be at the very top so it can intercept
    # pre-flight OPTIONS requests before any other middleware runs.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise must be immediately after SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# ==============================================================================
# DATABASE — PostgreSQL
# ==============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':     env_get('DB_NAME',     required=True),
        'USER':     env_get('DB_USER',     required=True),
        'PASSWORD': env_get('DB_PASSWORD', required=True),
        'HOST':     env_get('DB_HOST',     default='localhost'),
        'PORT':     env_get('DB_PORT',     default='5432'),
    }
}

# ==============================================================================
# AUTH
# ==============================================================================

AUTH_USER_MODEL = 'accounts.User'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

AUTHENTICATION_BACKENDS = [
    'accounts.backends.MultiFieldAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ==============================================================================
# INTERNATIONALISATION
# ==============================================================================

LANGUAGE_CODE = env_get('LANGUAGE_CODE', default='en-us')
TIME_ZONE     = env_get('TIME_ZONE',     default='UTC')

USE_I18N = True
USE_TZ   = True

# ==============================================================================
# STATIC & MEDIA FILES
# ==============================================================================

STATIC_URL  = env_get('STATIC_URL',  default='/static/')
STATIC_ROOT = BASE_DIR / env_get('STATIC_ROOT', default='staticfiles')

MEDIA_URL   = env_get('MEDIA_URL',   default='/media/')
MEDIA_ROOT  = BASE_DIR / env_get('MEDIA_ROOT',  default='media')

# WhiteNoise static file storage (Django 4.2+ STORAGES dict)
# Serves compressed, cache-busted static files in production without a CDN.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ==============================================================================
# CORS (django-cors-headers is already installed)
# ==============================================================================

CORS_ALLOWED_ORIGINS = env_get(
    "CORS_ALLOWED_ORIGINS",
    default=["http://localhost:5173"],
    cast=list,
)

# Allow all origins during local development (overrides CORS_ALLOWED_ORIGINS).
CORS_ALLOW_ALL_ORIGINS = env_get("CORS_ALLOW_ALL_ORIGINS", default=True, cast=bool)

# ==============================================================================
# LOGGING
# ==============================================================================

LOG_LEVEL = env_get('LOG_LEVEL', default='INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
}

# ==============================================================================
# DEFAULT PRIMARY KEY
# ==============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# DJANGO REST FRAMEWORK
# ==============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'EXCEPTION_HANDLER': 'core.domain.exception_handler.domain_exception_handler',
}

# ==============================================================================
# SIMPLE JWT
# ==============================================================================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS':  True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    # Custom token serializer that injects RBAC claims
    'TOKEN_OBTAIN_SERIALIZER': 'accounts.serializers.CustomTokenObtainPairSerializer',
}

# ==============================================================================
# DRF SPECTACULAR
# ==============================================================================

SPECTACULAR_SETTINGS = {
    'TITLE': 'LA Noire Police Department API',
    'DESCRIPTION': 'Backend API for the LA Noire police department management system.',
    'VERSION': '1.0.0',
}
