// TODO: Board (Detective Board) API calls
// - GET    /api/board/:caseId/                     → getBoard(caseId)
// - POST   /api/board/                             → createBoard(data)
// - GET    /api/board/:id/items/                   → listBoardItems(boardId)
// - POST   /api/board/:id/items/                   → addBoardItem(boardId, data)
// - PATCH  /api/board/items/:id/                   → updateBoardItem(itemId, data) (position)
// - DELETE /api/board/items/:id/                   → removeBoardItem(itemId)
// - POST   /api/board/:id/notes/                   → addBoardNote(boardId, data)
// - POST   /api/board/:id/connections/             → addConnection(boardId, data)
// - DELETE /api/board/connections/:id/             → removeConnection(connId)
// - POST   /api/board/:id/export/                  → exportBoardAsImage(boardId)
