// TODO: Suspects API calls
// - GET    /api/suspects/                          → listSuspects(params)
// - POST   /api/suspects/                          → createSuspect(data)
// - GET    /api/suspects/:id/                      → getSuspectDetail(id)
// - PATCH  /api/suspects/:id/                      → updateSuspect(id, data)
// - POST   /api/suspects/:id/interrogation/        → createInterrogation(id, data)
// - GET    /api/suspects/:id/interrogations/       → listInterrogations(suspectId)
// - POST   /api/suspects/:id/trial/                → createTrial(id, data)
// - GET    /api/suspects/most-wanted/              → getMostWanted()
// - POST   /api/suspects/bounty-tips/              → submitBountyTip(data)
// - PATCH  /api/suspects/bounty-tips/:id/review/   → reviewBountyTip(id, data)
// - POST   /api/suspects/:id/bail/                 → createBail(id, data)
// - GET    /api/suspects/:id/bail/verify/          → verifyBountyReward(nationalId, code)
