# Generated by Django 6.0.2 on 2026-02-21 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectiveBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detective_board', to='cases.case', verbose_name='Case')),
                ('detective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detective_boards', to=settings.AUTH_USER_MODEL, verbose_name='Detective')),
            ],
            options={
                'verbose_name': 'Detective Board',
                'verbose_name_plural': 'Detective Boards',
            },
        ),
        migrations.CreateModel(
            name='BoardNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='board.detectiveboard', verbose_name='Board')),
            ],
            options={
                'verbose_name': 'Board Note',
                'verbose_name_plural': 'Board Notes',
            },
        ),
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('position_x', models.FloatField(default=0.0, verbose_name='X Coordinate')),
                ('position_y', models.FloatField(default=0.0, verbose_name='Y Coordinate')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='board.detectiveboard', verbose_name='Board')),
            ],
            options={
                'verbose_name': 'Board Item',
                'verbose_name_plural': 'Board Items',
            },
        ),
        migrations.CreateModel(
            name='BoardConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('label', models.CharField(blank=True, default='', help_text='Optional annotation on the red line.', max_length=255, verbose_name='Connection Label')),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='board.boarditem', verbose_name='From Item')),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='board.boarditem', verbose_name='To Item')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='board.detectiveboard', verbose_name='Board')),
            ],
            options={
                'verbose_name': 'Board Connection',
                'verbose_name_plural': 'Board Connections',
            },
        ),
        migrations.AddIndex(
            model_name='boarditem',
            index=models.Index(fields=['content_type', 'object_id'], name='board_board_content_ecfb4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boardconnection',
            unique_together={('from_item', 'to_item')},
        ),
    ]
