# Generated by Django 6.0.2 on 2026-02-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectiveboard',
            options={'permissions': [('can_export_board', 'Can export detective board as image')], 'verbose_name': 'Detective Board', 'verbose_name_plural': 'Detective Boards'},
        ),
    ]
