# Generated by Django 6.0.2 on 2026-02-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_detectiveboard_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectiveboard',
            options={'permissions': [('can_export_board', 'Can export detective board as image'), ('can_create_board', 'Can create a detective board'), ('can_view_any_board', 'Supervisor: view boards on assigned cases')], 'verbose_name': 'Detective Board', 'verbose_name_plural': 'Detective Boards'},
        ),
    ]
