# Generated by Django 6.0.2 on 2026-02-21 23:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('national_id', models.CharField(blank=True, db_index=True, default='', max_length=10, verbose_name='National ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=15, verbose_name='Phone Number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='suspect_photos/%Y/%m/', verbose_name='Photo')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('description', models.TextField(blank=True, default='', verbose_name='Additional Description')),
                ('status', models.CharField(choices=[('wanted', 'Wanted'), ('arrested', 'Arrested'), ('under_interrogation', 'Under Interrogation'), ('under_trial', 'Under Trial'), ('convicted', 'Convicted'), ('acquitted', 'Acquitted'), ('released', 'Released on Bail')], db_index=True, default='wanted', max_length=20, verbose_name='Status')),
                ('wanted_since', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Wanted Since')),
                ('sergeant_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Sergeant Approval')),
                ('sergeant_rejection_message', models.TextField(blank=True, default='', verbose_name='Sergeant Rejection Message')),
                ('approved_by_sergeant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sergeant_approved_suspects', to=settings.AUTH_USER_MODEL, verbose_name='Approved By (Sergeant)')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='cases.case', verbose_name='Case')),
                ('identified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identified_suspects', to=settings.AUTH_USER_MODEL, verbose_name='Identified By (Detective)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspect_records', to=settings.AUTH_USER_MODEL, verbose_name='Linked User Account')),
            ],
            options={
                'verbose_name': 'Suspect',
                'verbose_name_plural': 'Suspects',
                'ordering': ['-wanted_since'],
            },
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('detective_guilt_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name="Detective's Guilt Score (1–10)")),
                ('sergeant_guilt_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name="Sergeant's Guilt Score (1–10)")),
                ('notes', models.TextField(blank=True, default='', verbose_name='Interrogation Notes')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='cases.case', verbose_name='Case')),
                ('detective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detective_interrogations', to=settings.AUTH_USER_MODEL, verbose_name='Detective')),
                ('sergeant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sergeant_interrogations', to=settings.AUTH_USER_MODEL, verbose_name='Sergeant')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='suspects.suspect', verbose_name='Suspect')),
            ],
            options={
                'verbose_name': 'Interrogation',
                'verbose_name_plural': 'Interrogations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BountyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('information', models.TextField(verbose_name='Submitted Information')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('officer_reviewed', 'Reviewed by Officer'), ('verified', 'Verified by Detective'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('unique_code', models.CharField(blank=True, help_text='Generated upon detective verification.', max_length=50, null=True, unique=True, verbose_name='Reward Claim Code')),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Reward Amount (Rials)')),
                ('is_claimed', models.BooleanField(default=False, verbose_name='Reward Claimed')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bounty_tips', to='cases.case', verbose_name='Case')),
                ('informant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tips', to=settings.AUTH_USER_MODEL, verbose_name='Informant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_reviewed_tips', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By (Officer)')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detective_verified_tips', to=settings.AUTH_USER_MODEL, verbose_name='Verified By (Detective)')),
                ('suspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bounty_tips', to='suspects.suspect', verbose_name='Suspect')),
            ],
            options={
                'verbose_name': 'Bounty Tip',
                'verbose_name_plural': 'Bounty Tips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Bail Amount (Rials)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Payment Reference')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_bails', to=settings.AUTH_USER_MODEL, verbose_name='Approved By (Sergeant)')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bails', to='cases.case', verbose_name='Case')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bails', to='suspects.suspect', verbose_name='Suspect')),
            ],
            options={
                'verbose_name': 'Bail',
                'verbose_name_plural': 'Bails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('verdict', models.CharField(choices=[('guilty', 'Guilty'), ('innocent', 'Innocent')], max_length=10, verbose_name='Verdict')),
                ('punishment_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Punishment Title')),
                ('punishment_description', models.TextField(blank=True, default='', verbose_name='Punishment Description')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='cases.case', verbose_name='Case')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='judged_trials', to=settings.AUTH_USER_MODEL, verbose_name='Judge')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='suspects.suspect', verbose_name='Suspect')),
            ],
            options={
                'verbose_name': 'Trial',
                'verbose_name_plural': 'Trials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='suspect',
            index=models.Index(fields=['status', 'wanted_since'], name='suspects_su_status_4ecd9d_idx'),
        ),
    ]
