# Generated by Django 6.0.2 on 2026-02-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bail',
            options={'ordering': ['-created_at'], 'permissions': [('can_set_bail_amount', 'Can determine bail/fine amount (Sergeant)')], 'verbose_name': 'Bail', 'verbose_name_plural': 'Bails'},
        ),
        migrations.AlterModelOptions(
            name='bountytip',
            options={'ordering': ['-created_at'], 'permissions': [('can_review_bounty_tip', 'Can do initial review of bounty tips (Officer)'), ('can_verify_bounty_tip', 'Can verify bounty tip information (Detective)')], 'verbose_name': 'Bounty Tip', 'verbose_name_plural': 'Bounty Tips'},
        ),
        migrations.AlterModelOptions(
            name='interrogation',
            options={'ordering': ['-created_at'], 'permissions': [('can_conduct_interrogation', 'Can conduct interrogation session'), ('can_score_guilt', 'Can assign guilt probability score (1-10)')], 'verbose_name': 'Interrogation', 'verbose_name_plural': 'Interrogations'},
        ),
        migrations.AlterModelOptions(
            name='suspect',
            options={'ordering': ['-wanted_since'], 'permissions': [('can_identify_suspect', 'Can identify and declare suspects (Detective)'), ('can_approve_suspect', 'Can approve/reject identified suspects (Sergeant)'), ('can_issue_arrest_warrant', 'Can issue arrest warrant (Sergeant)')], 'verbose_name': 'Suspect', 'verbose_name_plural': 'Suspects'},
        ),
        migrations.AlterModelOptions(
            name='trial',
            options={'ordering': ['-created_at'], 'permissions': [('can_render_verdict', 'Can give final guilty/innocent verdict (Captain/Chief)'), ('can_judge_trial', 'Can preside over trial and record punishment (Judge)')], 'verbose_name': 'Trial', 'verbose_name_plural': 'Trials'},
        ),
    ]
