# Generated by Django 6.0.2 on 2026-02-22 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0002_alter_bail_options_alter_bountytip_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reason', models.TextField(help_text='Justification for issuing the arrest warrant.', verbose_name='Reason for Warrant')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Issued At')),
                ('status', models.CharField(choices=[('active', 'Active'), ('executed', 'Executed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_warrants', to=settings.AUTH_USER_MODEL, verbose_name='Issued By (Sergeant)')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warrants', to='suspects.suspect', verbose_name='Suspect')),
            ],
            options={
                'verbose_name': 'Warrant',
                'verbose_name_plural': 'Warrants',
                'ordering': ['-issued_at'],
                'permissions': [('can_issue_arrest_warrant', 'Can issue arrest warrant (Sergeant)')],
            },
        ),
    ]
