# Generated by Django 6.0.2 on 2026-02-22 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0003_warrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='arrested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrested At'),
        ),
        migrations.CreateModel(
            name='SuspectStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('from_status', models.CharField(choices=[('wanted', 'Wanted'), ('arrested', 'Arrested'), ('under_interrogation', 'Under Interrogation'), ('under_trial', 'Under Trial'), ('convicted', 'Convicted'), ('acquitted', 'Acquitted'), ('released', 'Released on Bail')], max_length=20, verbose_name='Previous Status')),
                ('to_status', models.CharField(choices=[('wanted', 'Wanted'), ('arrested', 'Arrested'), ('under_interrogation', 'Under Interrogation'), ('under_trial', 'Under Trial'), ('convicted', 'Convicted'), ('acquitted', 'Acquitted'), ('released', 'Released on Bail')], max_length=20, verbose_name='New Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes / Reason')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspect_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='suspects.suspect', verbose_name='Suspect')),
            ],
            options={
                'verbose_name': 'Suspect Status Log',
                'verbose_name_plural': 'Suspect Status Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
