# Generated by Django 6.0.2 on 2026-02-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0004_suspect_arrested_at_suspectstatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='status',
            field=models.CharField(choices=[('wanted', 'Wanted'), ('arrested', 'Arrested'), ('under_interrogation', 'Under Interrogation'), ('pending_captain_verdict', 'Pending Captain Verdict'), ('pending_chief_approval', 'Pending Chief Approval'), ('under_trial', 'Under Trial'), ('convicted', 'Convicted'), ('acquitted', 'Acquitted'), ('released', 'Released on Bail')], db_index=True, default='wanted', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='suspectstatuslog',
            name='from_status',
            field=models.CharField(choices=[('wanted', 'Wanted'), ('arrested', 'Arrested'), ('under_interrogation', 'Under Interrogation'), ('pending_captain_verdict', 'Pending Captain Verdict'), ('pending_chief_approval', 'Pending Chief Approval'), ('under_trial', 'Under Trial'), ('convicted', 'Convicted'), ('acquitted', 'Acquitted'), ('released', 'Released on Bail')], max_length=30, verbose_name='Previous Status'),
        ),
        migrations.AlterField(
            model_name='suspectstatuslog',
            name='to_status',
            field=models.CharField(choices=[('wanted', 'Wanted'), ('arrested', 'Arrested'), ('under_interrogation', 'Under Interrogation'), ('pending_captain_verdict', 'Pending Captain Verdict'), ('pending_chief_approval', 'Pending Chief Approval'), ('under_trial', 'Under Trial'), ('convicted', 'Convicted'), ('acquitted', 'Acquitted'), ('released', 'Released on Bail')], max_length=30, verbose_name='New Status'),
        ),
    ]
