# Generated by Django 6.0.2 on 2026-02-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0005_alter_suspect_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='conditions',
            field=models.TextField(blank=True, default='', help_text='Optional conditions imposed on the bail release.', verbose_name='Bail Conditions'),
        ),
    ]
