# Generated by Django 6.0.2 on 2026-02-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0006_bail_add_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrant',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=10, verbose_name='Priority'),
        ),
    ]
