# Generated by Django 6.0.2 on 2026-02-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0007_warrant_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suspect',
            options={'ordering': ['-wanted_since'], 'permissions': [('can_identify_suspect', 'Can identify and declare suspects (Detective)'), ('can_approve_suspect', 'Can approve/reject identified suspects (Sergeant)'), ('can_issue_arrest_warrant', 'Can issue arrest warrant (Sergeant)'), ('can_scope_all_suspects', 'Unrestricted suspect visibility'), ('can_scope_assigned_suspects', 'See suspects on assigned cases (Detective)'), ('can_scope_supervised_suspects', 'See suspects on supervised cases (Sergeant)'), ('can_scope_examined_suspects', 'See suspects on examined cases (Coroner)'), ('can_scope_own_suspects', 'See suspects on own cases'), ('can_lookup_bounty_reward', 'Can look up bounty reward info')], 'verbose_name': 'Suspect', 'verbose_name_plural': 'Suspects'},
        ),
    ]
