# Generated by Django 6.0.2 on 2026-02-21 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('evidence_type', models.CharField(choices=[('testimony', 'Witness / Local Testimony'), ('biological', 'Biological / Medical'), ('vehicle', 'Vehicle'), ('identity', 'Identity Document'), ('other', 'Other Item')], db_index=True, max_length=20, verbose_name='Evidence Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='cases.case', verbose_name='Case')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_evidences', to=settings.AUTH_USER_MODEL, verbose_name='Registered By')),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentityEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('owner_full_name', models.CharField(max_length=255, verbose_name="Document Owner's Full Name")),
                ('document_details', models.JSONField(blank=True, default=dict, help_text='Dynamic key-value pairs describing the document.', verbose_name='Document Details (key-value)')),
            ],
            options={
                'verbose_name': 'Identity Evidence',
                'verbose_name_plural': 'Identity Evidences',
            },
            bases=('evidence.evidence',),
        ),
        migrations.CreateModel(
            name='TestimonyEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('statement_text', models.TextField(blank=True, default='', verbose_name='Statement Transcript')),
            ],
            options={
                'verbose_name': 'Testimony Evidence',
                'verbose_name_plural': 'Testimony Evidences',
            },
            bases=('evidence.evidence',),
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('file', models.FileField(upload_to='evidence_files/%Y/%m/', verbose_name='File')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=10, verbose_name='File Type')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Caption')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='evidence.evidence', verbose_name='Evidence')),
            ],
            options={
                'verbose_name': 'Evidence File',
                'verbose_name_plural': 'Evidence Files',
            },
        ),
        migrations.CreateModel(
            name='BiologicalEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('forensic_result', models.TextField(blank=True, default='', help_text='Filled by the Coroner or national-identity DB verification.', verbose_name='Forensic Result')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_biological_evidences', to=settings.AUTH_USER_MODEL, verbose_name='Verified By (Coroner)')),
            ],
            options={
                'verbose_name': 'Biological Evidence',
                'verbose_name_plural': 'Biological Evidences',
            },
            bases=('evidence.evidence',),
        ),
        migrations.CreateModel(
            name='VehicleEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('vehicle_model', models.CharField(max_length=100, verbose_name='Vehicle Model')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('license_plate', models.CharField(blank=True, default='', max_length=20, verbose_name='License Plate')),
                ('serial_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Serial Number')),
            ],
            options={
                'verbose_name': 'Vehicle Evidence',
                'verbose_name_plural': 'Vehicle Evidences',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('license_plate', ''), ('serial_number__gt', '')), models.Q(('license_plate__gt', ''), ('serial_number', '')), _connector='OR'), name='vehicle_plate_xor_serial')],
            },
            bases=('evidence.evidence',),
        ),
    ]
