# Generated by Django 6.0.2 on 2026-02-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biologicalevidence',
            options={'permissions': [('can_verify_evidence', 'Can verify biological/medical evidence (Coroner)'), ('can_register_forensic_result', 'Can register forensic examination result')], 'verbose_name': 'Biological Evidence', 'verbose_name_plural': 'Biological Evidences'},
        ),
    ]
