# Generated by Django 6.0.2 on 2026-02-22 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_alter_biologicalevidence_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceCustodyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('action_type', models.CharField(choices=[('checked_out', 'Checked Out'), ('checked_in', 'Checked In'), ('transferred', 'Transferred'), ('disposed', 'Disposed'), ('analysed', 'Analysed')], db_index=True, max_length=20, verbose_name='Action Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_logs', to='evidence.evidence', verbose_name='Evidence')),
                ('handled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_custody_actions', to=settings.AUTH_USER_MODEL, verbose_name='Handled By')),
            ],
            options={
                'verbose_name': 'Evidence Custody Log',
                'verbose_name_plural': 'Evidence Custody Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
