# Generated by Django 6.0.2 on 2026-02-21 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Case Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('crime_level', models.IntegerField(choices=[(1, 'Level 3 (Minor)'), (2, 'Level 2 (Medium)'), (3, 'Level 1 (Major)'), (4, 'Critical')], db_index=True, help_text='Determines severity and affects Most-Wanted ranking formula.', verbose_name='Crime Level')),
                ('status', models.CharField(choices=[('complaint_registered', 'Complaint Registered'), ('cadet_review', 'Under Cadet Review'), ('returned_to_complainant', 'Returned to Complainant'), ('officer_review', 'Under Officer Review'), ('returned_to_cadet', 'Returned to Cadet'), ('voided', 'Voided'), ('pending_approval', 'Pending Superior Approval'), ('open', 'Open'), ('investigation', 'Under Investigation'), ('suspect_identified', 'Suspect Identified'), ('sergeant_review', 'Under Sergeant Review'), ('arrest_ordered', 'Arrest Ordered'), ('interrogation', 'Under Interrogation'), ('captain_review', 'Under Captain Review'), ('chief_review', 'Under Chief Review'), ('judiciary', 'Referred to Judiciary'), ('closed', 'Closed')], db_index=True, default='complaint_registered', max_length=30, verbose_name='Current Status')),
                ('creation_type', models.CharField(choices=[('complaint', 'Via Complaint'), ('crime_scene', 'Via Crime-Scene Report')], max_length=20, verbose_name='Creation Type')),
                ('rejection_count', models.PositiveSmallIntegerField(default=0, help_text='If this reaches 3 the case is voided automatically.', verbose_name='Rejection Count')),
                ('incident_date', models.DateTimeField(blank=True, null=True, verbose_name='Incident Date/Time')),
                ('location', models.CharField(blank=True, default='', max_length=500, verbose_name='Incident Location')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Superior who approved the case (crime-scene workflow).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cases', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('assigned_captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_cases', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Captain')),
                ('assigned_detective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detective_cases', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Detective')),
                ('assigned_judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_cases', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Judge')),
                ('assigned_sergeant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sergeant_cases', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Sergeant')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseComplainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Complainant')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Approval Status')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainants', to='cases.case', verbose_name='Case')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_complainants', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Complainant')),
            ],
            options={
                'verbose_name': 'Case Complainant',
                'verbose_name_plural': 'Case Complainants',
            },
        ),
        migrations.CreateModel(
            name='CaseStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('from_status', models.CharField(choices=[('complaint_registered', 'Complaint Registered'), ('cadet_review', 'Under Cadet Review'), ('returned_to_complainant', 'Returned to Complainant'), ('officer_review', 'Under Officer Review'), ('returned_to_cadet', 'Returned to Cadet'), ('voided', 'Voided'), ('pending_approval', 'Pending Superior Approval'), ('open', 'Open'), ('investigation', 'Under Investigation'), ('suspect_identified', 'Suspect Identified'), ('sergeant_review', 'Under Sergeant Review'), ('arrest_ordered', 'Arrest Ordered'), ('interrogation', 'Under Interrogation'), ('captain_review', 'Under Captain Review'), ('chief_review', 'Under Chief Review'), ('judiciary', 'Referred to Judiciary'), ('closed', 'Closed')], max_length=30, verbose_name='Previous Status')),
                ('to_status', models.CharField(choices=[('complaint_registered', 'Complaint Registered'), ('cadet_review', 'Under Cadet Review'), ('returned_to_complainant', 'Returned to Complainant'), ('officer_review', 'Under Officer Review'), ('returned_to_cadet', 'Returned to Cadet'), ('voided', 'Voided'), ('pending_approval', 'Pending Superior Approval'), ('open', 'Open'), ('investigation', 'Under Investigation'), ('suspect_identified', 'Suspect Identified'), ('sergeant_review', 'Under Sergeant Review'), ('arrest_ordered', 'Arrest Ordered'), ('interrogation', 'Under Interrogation'), ('captain_review', 'Under Captain Review'), ('chief_review', 'Under Chief Review'), ('judiciary', 'Referred to Judiciary'), ('closed', 'Closed')], max_length=30, verbose_name='New Status')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message / Rejection Reason')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='cases.case', verbose_name='Case')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
            ],
            options={
                'verbose_name': 'Case Status Log',
                'verbose_name_plural': 'Case Status Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('national_id', models.CharField(db_index=True, max_length=10, verbose_name='National ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='cases.case', verbose_name='Case')),
            ],
            options={
                'verbose_name': 'Case Witness',
                'verbose_name_plural': 'Case Witnesses',
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['creation_type'], name='cases_case_creatio_a5a099_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'crime_level'], name='cases_case_status_99e34d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='casecomplainant',
            unique_together={('case', 'user')},
        ),
    ]
