# Generated by Django 6.0.2 on 2026-02-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at'], 'permissions': [('can_review_complaint', 'Can review incoming complaints (Cadet)'), ('can_approve_case', 'Can approve a case after review'), ('can_assign_detective', 'Can assign a detective to a case'), ('can_change_case_status', 'Can transition case workflow status'), ('can_forward_to_judiciary', 'Can forward solved case to judiciary'), ('can_approve_critical_case', 'Can approve critical-level cases (Chief)')], 'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
    ]
