# Generated by Django 6.0.2 on 2026-02-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at'], 'permissions': [('can_review_complaint', 'Can review incoming complaints (Cadet)'), ('can_approve_case', 'Can approve a case after review'), ('can_assign_detective', 'Can assign a detective to a case'), ('can_change_case_status', 'Can transition case workflow status'), ('can_forward_to_judiciary', 'Can forward solved case to judiciary'), ('can_approve_critical_case', 'Can approve critical-level cases (Chief)'), ('can_scope_all_cases', 'Unrestricted case visibility'), ('can_scope_supervised_cases', 'See supervised cases (Sergeant)'), ('can_scope_assigned_cases', 'See only assigned cases (Detective)'), ('can_scope_officer_cases', 'See post-complaint cases (Officer)'), ('can_scope_complaint_queue', 'See early complaint queue (Cadet)'), ('can_scope_judiciary_cases', 'See judiciary/closed cases (Judge)'), ('can_scope_own_cases', 'See only own-involved cases'), ('can_scope_coroner_cases', 'See cases with unverified bio evidence (Coroner)'), ('can_create_crime_scene', 'Can create a crime-scene case'), ('can_auto_approve_crime_scene', 'Crime-scene cases auto-open on creation'), ('can_view_case_report', 'Can access the full case report'), ('can_be_assigned_detective', 'Can be assigned as detective'), ('can_be_assigned_sergeant', 'Can be assigned as sergeant'), ('can_be_assigned_captain', 'Can be assigned as captain'), ('can_be_assigned_judge', 'Can be assigned as judge')], 'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
    ]
