# Generated by Django 6.0.2 on 2026-02-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('complaint_registered', 'Complaint Registered'), ('cadet_review', 'Under Cadet Review'), ('returned_to_complainant', 'Returned to Complainant'), ('officer_review', 'Under Officer Review'), ('returned_to_cadet', 'Returned to Cadet'), ('voided', 'Voided'), ('pending_approval', 'Pending Superior Approval'), ('open', 'Open'), ('investigation', 'Under Investigation'), ('judiciary', 'Referred to Judiciary'), ('closed', 'Closed')], db_index=True, default='complaint_registered', max_length=30, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='casestatuslog',
            name='from_status',
            field=models.CharField(choices=[('complaint_registered', 'Complaint Registered'), ('cadet_review', 'Under Cadet Review'), ('returned_to_complainant', 'Returned to Complainant'), ('officer_review', 'Under Officer Review'), ('returned_to_cadet', 'Returned to Cadet'), ('voided', 'Voided'), ('pending_approval', 'Pending Superior Approval'), ('open', 'Open'), ('investigation', 'Under Investigation'), ('judiciary', 'Referred to Judiciary'), ('closed', 'Closed')], max_length=30, verbose_name='Previous Status'),
        ),
        migrations.AlterField(
            model_name='casestatuslog',
            name='to_status',
            field=models.CharField(choices=[('complaint_registered', 'Complaint Registered'), ('cadet_review', 'Under Cadet Review'), ('returned_to_complainant', 'Returned to Complainant'), ('officer_review', 'Under Officer Review'), ('returned_to_cadet', 'Returned to Cadet'), ('voided', 'Voided'), ('pending_approval', 'Pending Superior Approval'), ('open', 'Open'), ('investigation', 'Under Investigation'), ('judiciary', 'Referred to Judiciary'), ('closed', 'Closed')], max_length=30, verbose_name='New Status'),
        ),
    ]
