# Generated by Django 6.0.2 on 2026-02-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_full_dashboard', 'Full department dashboard access'), ('can_search_all', 'Unrestricted global search')], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
